//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasedemo
{
    public class Student
    {
        public long StudentID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    }
}